# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGbPR806itbmlnDkexNM0DNnY6qXEWAf
"""

def can_cross(T, cases):
    results = []

    for t in range(T):
        N, K = cases[t][0]
        S = cases[t][1]

        S.sort()  # Sort crossing times
        total_time = 0

        if N == 1:
            total_time = S[0]  # Only one person crosses
        elif N == 2:
            total_time = S[0]  # The faster can take the other in the wheelbarrow
        elif N == 3:
            total_time = S[0] + S[0] + S[0]  # One goes with the wheelbarrow, then the other two cross
        else:
            while N > 3:
                total_time += S[0]+S[0]
                N -= 1

            # Handle the last three travelers
            if N == 3:
                total_time += S[0] + S[0] + S[0]  # One goes with the wheelbarrow
            elif N == 2:
                total_time += S[0]  # Two cross together
            elif N == 1:
                total_time += S[0]  # Only one crosses

        results.append(f"Case #{t + 1}: {'YES' if total_time <= K else 'NO'}")

    return results

def main():
    # Read from input file
    with open('input1.txt', 'r') as infile:
        T = int(infile.readline().strip())
        cases = []

        for _ in range(T):
            N, K = map(int, infile.readline().strip().split())
            S = [int(infile.readline().strip()) for _ in range(N)]
            cases.append(((N, K), S))

    # Get results
    results = can_cross(T, cases)

    # Write to output file
    with open('output1.txt', 'w') as outfile:
        for result in results:
            outfile.write(result + '\n')

if __name__ == "__main__":
    main()